### ISSUE TITLE
Update github repository

### ISSUE THREAD

**Issue by roguecat0** [zeskeertwee/atletiek-nu-api#4]
It seems this gitrepository is a out of date comared to the API provided on you webside eg.
local api /competitions/results/:id:
``` json
{
      "participant_id": 322029,
      "name": "Senioren 2e - 3e Divisi...otie/Degradatie [2016]"
}
```
atnapi.juandomingo.net /competitions/results/:id:
``` json
{
      "participant_id": 322029,
      "name": "Senioren 2e - 3e Divisi...otie/Degradatie [2016]",
      "location": {
          "country": "Netherlands",
          "continent": "Europe",
          "place": "Eindhoven",
          "flag_img_url": "https://www.athletics.app/img/country-flags/png100px/nl.png"
      },
      "date": "2016-09-18"
 },
```
Could you push those changes to the repo? 
As I'd like to update the local http api endpoints

**Comment by zeskeertwee** [comment]
It seems i forgot to push some commits from my laptop, i think ffb087d is the one you were looking for specifically. Thanks for notifying me!

PS. i'm not using this library much now, but if you find a page that fails to scrape (which isn't uncommon), please do make an issue (or PR, if you've got a fix)!.
